default.packagist.github.client_id = 'notarealclientid'
default.packagist.github.client_secret = 'notarealsecretid'
default.packagist.user = 'vagrant'
default.packagist.repository = 'https://github.com/composer/packagist'
default.packagist.ref = 'master'
default.packagist.web_root = '/var/www'
default.packagist.packagist_host = 'localhost'
