name             'packagist_cookbook'
maintainer       'Shogo Kawahara'
maintainer_email 'kawahara@bucyou.net'
license          'MIT License'
description      'Make packagist clone'
version          '0.1.0'
